import express from "express";
import dotenv from "dotenv";
import cors from "cors";
import path from "path";
import { fileURLToPath } from "url";

import identifyRoute from "./src/routes/identify.js";
import devicesRoute from "./src/routes/devices.js";
import locationRoute from "./src/routes/location.js";
import resetSimRoute from "./src/routes/resetSim.js";
import reportRoute from "./src/routes/report.js";

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

const PORT = process.env.PORT || 8080;

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 1. Backend API Routes
app.use("/api/identify", identifyRoute);
app.use("/api/devices", devicesRoute);
app.use("/api/location", locationRoute);
app.use("/api/ticket/reset-sim", resetSimRoute);
app.use("/api/ticket/report", reportRoute);

app.get("/api/config", (req, res) => {
  res.json({
    lang: process.env.APP_LANG || "en",
    environment: "DEMO",
    entityId: process.env.GLPI_ENTITY_ID || "1"
  });
});

// 2. Serve Static Assets generated by Nitro
const publicPath = path.join(__dirname, "frontend", ".output", "public");
app.use(express.static(publicPath));

// 3. Import Nitro SSR Server Module
let nitroModule = null;
try {
  nitroModule = await import("./frontend/.output/server/index.mjs");
  console.log("Loaded Nitro SSR module successfully.");
} catch (err) {
  console.error("Could not load Nitro SSR server bundle:", err);
}

// Helper to handle Web Standard fetch responses in Express
async function handleWebFetch(fetchFn, req, res) {
  const protocol = req.protocol || "http";
  const host = req.get("host") || "localhost:8080";
  const url = `${protocol}://${host}${req.originalUrl || req.url}`;

  const headers = new Headers();
  for (const [k, v] of Object.entries(req.headers)) {
    if (v !== undefined) {
      if (Array.isArray(v)) v.forEach((val) => headers.append(k, val));
      else headers.set(k, v);
    }
  }

  const init = { method: req.method, headers };
  if (req.method !== "GET" && req.method !== "HEAD" && req.body) {
    init.body = typeof req.body === "string" ? req.body : JSON.stringify(req.body);
  }

  const webReq = new Request(url, init);
  const webRes = await fetchFn(webReq);

  res.status(webRes.status);
  webRes.headers.forEach((val, key) => {
    if (key.toLowerCase() !== "content-encoding") {
      res.setHeader(key, val);
    }
  });

  if (webRes.body) {
    const reader = webRes.body.getReader();
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      res.write(value);
    }
    res.end();
  } else {
    res.end();
  }
}

// 4. Delegate non-API requests to TanStack Start / Nitro SSR
app.use(async (req, res, next) => {
  if (req.path.startsWith("/api")) return next();

  if (!nitroModule) {
    return res.status(404).send("Frontend SSR bundle not available.");
  }

  try {
    const handler = nitroModule.handler || nitroModule.default?.handler;
    const fetchFn = nitroModule.fetch || nitroModule.default?.fetch || (typeof nitroModule.default === "function" ? nitroModule.default : null);

    // Strategy A: Direct Node (req, res) handler
    if (typeof handler === "function" && handler.length >= 2) {
      return await handler(req, res);
    }

    // Strategy B: Native Web Fetch handler
    if (typeof fetchFn === "function") {
      return await handleWebFetch(fetchFn, req, res);
    }

    // Strategy C: Direct fallback execution
    if (typeof handler === "function") {
      return await handler(req, res);
    }

    res.status(500).send("No valid Nitro handler found in build output.");
  } catch (ssrErr) {
    console.error("Nitro SSR execution error:", ssrErr);
    res.status(500).send("SSR Render Error");
  }
});

app.listen(PORT, () => {
  console.log(`FDNY Kiosk Server running on http://localhost:${PORT}`);
});