import express from "express";
import dotenv from "dotenv";
import cors from "cors";
import path from "path";
import { fileURLToPath } from "url";

import identifyRoute from "./src/routes/identify.js";
import devicesRoute from "./src/routes/devices.js";
import locationRoute from "./src/routes/location.js";
import resetSimRoute from "./src/routes/resetSim.js";
import reportRoute from "./src/routes/report.js";

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

const PORT = process.env.PORT || 8080;

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 1. Backend API Routes
app.use("/api/identify", identifyRoute);
app.use("/api/devices", devicesRoute);
app.use("/api/location", locationRoute);
app.use("/api/ticket/reset-sim", resetSimRoute);
app.use("/api/ticket/report", reportRoute);

app.get("/api/config", (req, res) => {
  res.json({
    lang: process.env.APP_LANG || "en",
    environment: "DEMO",
    entityId: process.env.GLPI_ENTITY_ID || "1"
  });
});

// 2. Serve Static Assets generated by Nitro
const publicPath = path.join(__dirname, "frontend", ".output", "public");
app.use(express.static(publicPath));

// 3. Load Nitro SSR Server Bundle for Frontend Routes
let nitroHandler = null;
try {
  const nitroModule = await import("./frontend/.output/server/index.mjs");
  nitroHandler = nitroModule.handler || nitroModule.default;
} catch (err) {
  console.error("Could not load Nitro SSR server bundle:", err);
}

// Delegate non-API page requests to TanStack Start / Nitro SSR
app.use((req, res, next) => {
  if (req.path.startsWith("/api")) return next();

  if (nitroHandler) {
    return nitroHandler(req, res);
  }
  res.status(404).send("Frontend SSR bundle not available.");
});

app.listen(PORT, () => {
  console.log(`FDNY Kiosk Server running on http://localhost:${PORT}`);
});