/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpRouteImport } from './routes/help'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyCasesRouteImport } from './routes/my-cases'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportTicketRouteImport } from './routes/report-ticket'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffCasesRouteImport } from './routes/staff/cases'
import { Route as StaffDevicesRouteImport } from './routes/staff/devices'
import { Route as StaffInventoryRouteImport } from './routes/staff/inventory'
import { Route as StaffReportForRouteImport } from './routes/staff/report-for'
import { Route as StaffReportsRouteImport } from './routes/staff/reports'
import { Route as StaffSettingsRouteImport } from './routes/staff/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCasesRoute = MyCasesRouteImport.update({
  id: '/my-cases',
  path: '/my-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportTicketRoute = ReportTicketRouteImport.update({
  id: '/report-ticket',
  path: '/report-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffCasesRoute = StaffCasesRouteImport.update({
  id: '/staff/cases',
  path: '/staff/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDevicesRoute = StaffDevicesRouteImport.update({
  id: '/staff/devices',
  path: '/staff/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffInventoryRoute = StaffInventoryRouteImport.update({
  id: '/staff/inventory',
  path: '/staff/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffReportForRoute = StaffReportForRouteImport.update({
  id: '/staff/report-for',
  path: '/staff/report-for',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffReportsRoute = StaffReportsRouteImport.update({
  id: '/staff/reports',
  path: '/staff/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSettingsRoute = StaffSettingsRouteImport.update({
  id: '/staff/settings',
  path: '/staff/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/login': typeof LoginRoute
  '/my-cases': typeof MyCasesRoute
  '/profile': typeof ProfileRoute
  '/report-ticket': typeof ReportTicketRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/staff/cases': typeof StaffCasesRoute
  '/staff/devices': typeof StaffDevicesRoute
  '/staff/inventory': typeof StaffInventoryRoute
  '/staff/report-for': typeof StaffReportForRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/login': typeof LoginRoute
  '/my-cases': typeof MyCasesRoute
  '/profile': typeof ProfileRoute
  '/report-ticket': typeof ReportTicketRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/staff/cases': typeof StaffCasesRoute
  '/staff/devices': typeof StaffDevicesRoute
  '/staff/inventory': typeof StaffInventoryRoute
  '/staff/report-for': typeof StaffReportForRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/login': typeof LoginRoute
  '/my-cases': typeof MyCasesRoute
  '/profile': typeof ProfileRoute
  '/report-ticket': typeof ReportTicketRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/staff/cases': typeof StaffCasesRoute
  '/staff/devices': typeof StaffDevicesRoute
  '/staff/inventory': typeof StaffInventoryRoute
  '/staff/report-for': typeof StaffReportForRoute
  '/staff/reports': typeof StaffReportsRoute
  '/staff/settings': typeof StaffSettingsRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/knowledge-base'
    | '/login'
    | '/my-cases'
    | '/profile'
    | '/report-ticket'
    | '/services'
    | '/settings'
    | '/staff/cases'
    | '/staff/devices'
    | '/staff/inventory'
    | '/staff/report-for'
    | '/staff/reports'
    | '/staff/settings'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/knowledge-base'
    | '/login'
    | '/my-cases'
    | '/profile'
    | '/report-ticket'
    | '/services'
    | '/settings'
    | '/staff/cases'
    | '/staff/devices'
    | '/staff/inventory'
    | '/staff/report-for'
    | '/staff/reports'
    | '/staff/settings'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/knowledge-base'
    | '/login'
    | '/my-cases'
    | '/profile'
    | '/report-ticket'
    | '/services'
    | '/settings'
    | '/staff/cases'
    | '/staff/devices'
    | '/staff/inventory'
    | '/staff/report-for'
    | '/staff/reports'
    | '/staff/settings'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRoute: typeof HelpRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  LoginRoute: typeof LoginRoute
  MyCasesRoute: typeof MyCasesRoute
  ProfileRoute: typeof ProfileRoute
  ReportTicketRoute: typeof ReportTicketRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  StaffCasesRoute: typeof StaffCasesRoute
  StaffDevicesRoute: typeof StaffDevicesRoute
  StaffInventoryRoute: typeof StaffInventoryRoute
  StaffReportForRoute: typeof StaffReportForRoute
  StaffReportsRoute: typeof StaffReportsRoute
  StaffSettingsRoute: typeof StaffSettingsRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-cases': {
      id: '/my-cases'
      path: '/my-cases'
      fullPath: '/my-cases'
      preLoaderRoute: typeof MyCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-ticket': {
      id: '/report-ticket'
      path: '/report-ticket'
      fullPath: '/report-ticket'
      preLoaderRoute: typeof ReportTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/cases': {
      id: '/staff/cases'
      path: '/staff/cases'
      fullPath: '/staff/cases'
      preLoaderRoute: typeof StaffCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/devices': {
      id: '/staff/devices'
      path: '/staff/devices'
      fullPath: '/staff/devices'
      preLoaderRoute: typeof StaffDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/inventory': {
      id: '/staff/inventory'
      path: '/staff/inventory'
      fullPath: '/staff/inventory'
      preLoaderRoute: typeof StaffInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/report-for': {
      id: '/staff/report-for'
      path: '/staff/report-for'
      fullPath: '/staff/report-for'
      preLoaderRoute: typeof StaffReportForRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/reports': {
      id: '/staff/reports'
      path: '/staff/reports'
      fullPath: '/staff/reports'
      preLoaderRoute: typeof StaffReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/settings': {
      id: '/staff/settings'
      path: '/staff/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof StaffSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRoute: HelpRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  LoginRoute: LoginRoute,
  MyCasesRoute: MyCasesRoute,
  ProfileRoute: ProfileRoute,
  ReportTicketRoute: ReportTicketRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  StaffCasesRoute: StaffCasesRoute,
  StaffDevicesRoute: StaffDevicesRoute,
  StaffInventoryRoute: StaffInventoryRoute,
  StaffReportForRoute: StaffReportForRoute,
  StaffReportsRoute: StaffReportsRoute,
  StaffSettingsRoute: StaffSettingsRoute,
  StaffIndexRoute: StaffIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
